spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cr9yjdhvew93.ap-southeast-1.rds.amazonaws.com:5432/teamkakana
    username: postgres
    password: teamkakanaproject
  servlet:
    multipart:
      max-file-size: 50MB